### ISSUE TITLE
Include companies that are not announced

### ISSUE THREAD

**Issue by fchamicapereira** [sinfo/ng-sinfo-webapp#110]

**Comment by johnytiago** [comment]
Companies that are not announced by Deck are not visible in the promotion page at the web app. This should not be the case. We should include all companies, maybe even partners and service providers, thus allowing for more complex interactions. At the moment we only list the companies that follow the standard advertisement packages. 
By including all companies we are giving access to companies that do not include CVs in their package. Hence, the linking functionality should not be open to them. **The signing one**, on the other side, is required by the conference so that the general workflow is not disturbed. This one must be open to any company/partner present in the conf.
